server {
    listen 80;

    location /reseller/ {
        proxy_pass http://frontend:80/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;

        # Rewrite agar path /reseller/... tidak memotong file path di frontend
        rewrite ^/reseller/(.*)$ /$1 break;
    }

    location /images/ {
        proxy_pass http://backend:5000/images/;
    }

    location /submit {
        proxy_pass http://backend:5000/submit;
    }
}