server {
    listen 80;
    server_name localhost;

    # Forward semua static request ke service frontend
    location / {
        proxy_pass http://frontend:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Forward form submission ke backend Flask
    #location /submit {
    #    proxy_pass http://backend:5000;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Real-IP $remote_addr;
    #}
}
