version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: fstore_lp_frontend
    expose:
      - "3000"

  #backend:
  #  build: ./backend
  #  container_name: fstore_lp_backend
  #  expose:
  #    - "5000"

  nginx:
    image: nginx:alpine
    container_name: fstore_lp_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      #- backend
